# prometheus global config 
global:
    scrape_interval: 15s 
    scrape_timeout: 10s
scrape_configs:
# Scrape the Node Exporter every 5 seconds. 
    - job_name: 'node'
      scrape_interval: 5s
      metrics_path: /metrics
      static_configs:
          - targets: ['ftp-file:9182','mobile-app1:9182','mobile-app2:9182','mongodb:9182','nginx:9182','report1:9182','report2:9182','sql-server:9182','web-app:9182']

